version: 0.2

# CodeBuild specification for building Erlang releases
# This builds the Erlang release in a large CodeBuild instance and uploads to S3

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Activating pre-installed Erlang/OTP..."
      - source /usr/local/erlang/activate
      - export PATH=/usr/local/erlang/bin:$PATH
      - erl -version
      - rebar3 version

  pre_build:
    commands:
      - echo "Build started on $(date)"
      - export PATH=/usr/local/erlang/bin:$PATH
      - erl -version
      - echo "Building in $(pwd)"
      - ls -la

  build:
    commands:
      - echo "Building Erlang release with ERTS (prod mode)..."
      - export PATH=/usr/local/erlang/bin:$PATH
      - rebar3 as prod tar
      - echo "Build completed"

  post_build:
    commands:
      - echo "Build completed on $(date)"
      - TARBALL=$(find _build/prod/rel -name "*.tar.gz" | head -1)
      - if [ -z "$TARBALL" ]; then echo "Error - tarball not found" && exit 1; fi
      - echo "Built tarball - $TARBALL"
      - TARBALL_NAME=$(basename "$TARBALL")
      - echo "Tarball name - $TARBALL_NAME"
      - echo "Preparing deployment bundle..."
      - mkdir -p bundle
      - echo "Extracting Erlang release..."
      - tar -xzf "$TARBALL" -C bundle/
      - echo "Adding CodeDeploy files..."
      - cp config/aws/appspec.yml bundle/appspec.yml
      - mkdir -p bundle/scripts
      - cp config/aws/codedeploy/*.sh bundle/scripts/
      - echo "Creating final deployment bundle..."
      - cd bundle && tar -czf ../hello_erlang.tar.gz . && cd ..
      - echo "Deployment bundle created"
      - ls -lh hello_erlang.tar.gz
      - echo "Deployment bundle contents:"
      - tar -tzf hello_erlang.tar.gz | head -20

artifacts:
  files:
    - 'hello_erlang.tar.gz'
  name: release-$(date +%Y%m%d-%H%M%S)
  discard-paths: yes

cache:
  paths:
    - '/root/.cache/rebar3/**/*'
